/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Jean Pierre
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        passwordFieldRectBackground1 = new org.edisoncor.gui.passwordField.PasswordFieldRectBackground();
        textFieldRectBackground1 = new org.edisoncor.gui.textField.TextFieldRectBackground();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        buttonAction1 = new org.edisoncor.gui.button.ButtonAction();
        buttonAction2 = new org.edisoncor.gui.button.ButtonAction();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        panel1.setBackground(new java.awt.Color(204, 204, 204));
        panel1.setColorPrimario(new java.awt.Color(0, 0, 0));
        panel1.setColorSecundario(new java.awt.Color(51, 51, 51));
        panel1.setLayout(null);

        panelCurves1.setBackground(new java.awt.Color(204, 204, 204));
        panelCurves1.setLayout(null);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user2.png"))); // NOI18N
        panelImage2.setInheritsPopupMenu(true);
        panelImage2.setLayout(null);
        panelCurves1.add(panelImage2);
        panelImage2.setBounds(160, 70, 130, 120);

        passwordFieldRectBackground1.setDescripcion("Contraseña"); // NOI18N
        panelCurves1.add(passwordFieldRectBackground1);
        passwordFieldRectBackground1.setBounds(160, 310, 230, 40);

        textFieldRectBackground1.setDescripcion("Usuario");
        panelCurves1.add(textFieldRectBackground1);
        textFieldRectBackground1.setBounds(160, 250, 230, 40);

        labelMetric1.setText("Contraseña.");
        panelCurves1.add(labelMetric1);
        labelMetric1.setBounds(40, 310, 120, 40);

        labelMetric2.setText("Usuario.");
        panelCurves1.add(labelMetric2);
        labelMetric2.setBounds(40, 250, 120, 40);

        buttonAction1.setBackground(new java.awt.Color(0, 0, 0));
        buttonAction1.setText("Registar");
        buttonAction1.setMain(true);
        panelCurves1.add(buttonAction1);
        buttonAction1.setBounds(290, 370, 116, 35);

        buttonAction2.setText("Inicias Sesión");
        buttonAction2.setActionCommand("Iniciar Sesión");
        buttonAction2.setMain(true);
        panelCurves1.add(buttonAction2);
        buttonAction2.setBounds(150, 370, 116, 35);

        panel1.add(panelCurves1);
        panelCurves1.setBounds(0, 0, 440, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(454, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAction buttonAction1;
    private org.edisoncor.gui.button.ButtonAction buttonAction2;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private org.edisoncor.gui.passwordField.PasswordFieldRectBackground passwordFieldRectBackground1;
    private org.edisoncor.gui.textField.TextFieldRectBackground textFieldRectBackground1;
    // End of variables declaration//GEN-END:variables
}
